'use client';
import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {Plan,Item,Point,analyze,chairPose,chairCollision,polygon,drawerZones,bounds,outside,overlap} from '@/lib/planner/model';
export type View='3d'|'plan'|'room';
export type SceneProps={plan:Plan;selected:string;view:View;grid:boolean;dimensions:boolean;drawers:boolean;envelope:boolean;night:boolean;progress:number;snap:boolean;reset:number;onSelect:(id:string)=>void;onMove:(id:string,x:number,z:number,final:boolean)=>void;onReady?:(capture:()=>string)=>void};
const teal='#137c75',amber='#bb801f';
function mat(color:string,roughness=.8){return new T.MeshStandardMaterial({color,roughness});}
function box(g:T.Group,w:number,h:number,d:number,x:number,y:number,z:number,m:T.Material,round=0){const mesh=new T.Mesh(round?new RoundedBoxGeometry(w,h,d,3,round):new T.BoxGeometry(w,h,d),m);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;g.add(mesh);return mesh;}
function line(g:T.Group,pts:number[][],color:string,dashed=false){const geo=new T.BufferGeometry().setFromPoints(pts.map(p=>new T.Vector3(...p as [number,number,number])));const l=new T.Line(geo,dashed?new T.LineDashedMaterial({color,dashSize:2,gapSize:1,toneMapped:false}):new T.LineBasicMaterial({color,toneMapped:false}));if(dashed)l.computeLineDistances();g.add(l);return l;}
function label(g:T.Group,text:string,x:number,y:number,z:number,color='#314042',scale=1){const c=document.createElement('canvas');const measure=c.getContext('2d')!;measure.font='600 34px Arial';c.width=Math.ceil(measure.measureText(text).width)+32;c.height=68;const ctx=c.getContext('2d')!;ctx.font='600 34px Arial';ctx.fillStyle='rgba(255,255,255,.96)';ctx.beginPath();ctx.roundRect(0,0,c.width,68,8);ctx.fill();ctx.fillStyle=color;ctx.textAlign='center';ctx.fillText(text,c.width/2,46);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;const sp=new T.Sprite(new T.SpriteMaterial({map:tex,depthTest:false,transparent:true,toneMapped:false}));sp.scale.set(c.width/68*7.2*scale,7.2*scale,1);sp.position.set(x,y,z);sp.renderOrder=9;g.add(sp);return sp;}
function dimension(g:T.Group,a:number[],b:number[],text:string,color='#5b6d70'){line(g,[a,b],color);const dx=b[0]-a[0],dz=b[2]-a[2],len=Math.hypot(dx,dz)||1;for(const p of [a,b])line(g,[[p[0]-dz/len*1.8,p[1],p[2]+dx/len*1.8],[p[0]+dz/len*1.8,p[1],p[2]-dx/len*1.8]],color);label(g,text,(a[0]+b[0])/2,(a[1]+b[1])/2+3,(a[2]+b[2])/2,color,.85);}
function flatPoly(g:T.Group,points:Point[],color:string,opacity=.1){const s=new T.Shape();points.forEach((p,i)=>i?s.lineTo(p.x,-p.z):s.moveTo(p.x,-p.z));s.closePath();const mesh=new T.Mesh(new T.ShapeGeometry(s),new T.MeshBasicMaterial({color,transparent:true,opacity,side:T.DoubleSide,depthWrite:false}));mesh.rotation.x=-Math.PI/2;mesh.position.y=.32;g.add(mesh);line(g,[...points,points[0]].map(p=>[p.x,.5,p.z]),color,true);}
function woodTexture(color:string){const c=document.createElement('canvas');c.width=512;c.height=512;const ctx=c.getContext('2d')!;ctx.fillStyle=color;ctx.fillRect(0,0,512,512);let seed=23;const rnd=()=>{seed=(seed*16807)%2147483647;return seed/2147483647;};for(let i=0;i<1500;i++){const y=rnd()*512;ctx.strokeStyle=rnd()>.5?'rgba(255,255,255,.055)':'rgba(0,0,0,.06)';ctx.lineWidth=rnd()*1.8;ctx.beginPath();ctx.moveTo(0,y);for(let x=0;x<=512;x+=16)ctx.lineTo(x,y+Math.sin(x*.02+i)*rnd()*4);ctx.stroke();}const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;tex.wrapS=tex.wrapT=T.RepeatWrapping;return tex;}
function furniture(g:T.Group,item:Item,selected:boolean,plan:Plan,drawers:boolean,invalid=false){const {w,d,h}=item;g.position.set(item.x,0,item.z);g.rotation.y=item.r*Math.PI/180;g.userData.itemId=item.id;const dark=mat(item.color,.62),edge=mat('#1c2020'),silver=mat('#7d8383',.34),fabric=mat('#e8e5dc',.94),white=mat('#f8f5ed',1),clay=mat('#a9664f',.98);
 if(item.kind==='bed'){
  const hd=Math.min(11,d*.15),bodyD=d-hd;box(g,w,15.5,bodyD,0,9.25,hd/2,dark,.35);box(g,w,h,hd,0,h/2,-d/2+hd/2,dark,.25);box(g,w-3,1,hd+1,0,h-.8,-d/2+hd/2,edge,.2);
  for(const side of [-1,1]){for(const z of [-d/2+hd+bodyD*.25,-d/2+hd+bodyD*.75]){const ext=drawers?plan.drawerExtension:0;box(g,2,12,bodyD/2-2,side*(w/2+ext-1),9,z,dark,.2);box(g,1,1.1,12,side*(w/2+ext+.15),13,z,silver,.12);if(ext>0)box(g,ext,1,bodyD/2-3,side*(w/2+ext/2),4,z,mat('#c5b6a0'));}for(const yy of [h*.35,h*.65])box(g,.7,1,hd-2,side*(w/2+.1),yy,-d/2+hd/2,silver);}
  box(g,w-3,8,bodyD-3,0,20,hd/2,fabric,2);box(g,w-4,3,bodyD-5,0,24,hd/2,white,1.5);
  for(const x of [-w*.235,w*.235]){const pillow=box(g,w*.43,5,17,x,28,-d/2+hd+12,white,2);pillow.rotation.y=x<0?-.035:.035;}
  box(g,w-2,1.3,24,0,26,d/2-18,clay,.55);for(let i=0;i<15;i++)box(g,w-2,.11,.12,0,26.75,d/2-30+i*1.6,mat('#b97860'));box(g,w,18.5,1.5,0,9.25,d/2-.75,dark,.2);
 } else if(item.kind==='desk'){
  const wood=new T.MeshStandardMaterial({map:woodTexture(item.color),roughness:.7});box(g,w,1.25,d,0,h-.625,0,wood,.25);box(g,w,1.3,4.75,0,h-.6,d/2-2.375,mat('#383d3b'),.1);
  for(const s of [-1,1]){const x=s*(w-8)/2;box(g,2.5,h-3,3,x,(h-3)/2,0,edge,.2);box(g,3,1.7,Math.min(22,d),x,1,0,edge,.4);box(g,3.3,Math.max(5,h*.38),3.6,x,h*.2,0,dark,.2);}box(g,w-8,3,2,0,h-5,0,edge,.2);box(g,5,1,2,w/2-6,h-1.7,-d/2,edge,.2);
  const monitor=mat('#272d2f',.3);box(g,13,.4,7,0,h+.25,2,monitor,.4);box(g,1.5,6,1.5,0,h+3,4,monitor);box(g,23,13,.7,0,h+11,5,monitor,.5);box(g,21.8,11.8,.1,0,h+11,4.6,mat('#7e9996'),.2);box(g,16,.4,5,0,h+.3,-d/2+5,mat('#c7c9c4'),.35);
 } else if(item.kind==='nightstand'){
  box(g,w,1,d,0,h-.5,0,dark,.15);for(const s of [-1,1])box(g,1,h,d,s*(w/2-.5),h/2,0,dark,.1);box(g,w-1,1,d,0,1,0,dark);box(g,w-1,1,d,0,h*.48,0,dark);box(g,w-2,h*.4,1,0,h*.73,d/2-.4,dark,.2);box(g,w-4,1,.8,0,h*.85,d/2+.3,silver,.1);box(g,w-2,h-2,.7,0,h/2,-d/2+.4,dark);
 }else{box(g,w,h,d,0,h/2,0,dark,.4);line(g,[[0,0,d/2+.1],[0,h,d/2+.1]],'#7d827f');box(g,1,8,1,2,h*.6,d/2+.5,silver,.2);}
 if(selected||invalid){const outline=invalid?'#c2513e':teal;const points=[[-w/2,.8,-d/2],[w/2,.8,-d/2],[w/2,.8,d/2],[-w/2,.8,d/2],[-w/2,.8,-d/2]];line(g,points,outline);for(const p of points.slice(0,4))box(g,1.6,.7,1.6,p[0],1,p[2],new T.MeshBasicMaterial({color:outline,toneMapped:false}));}
}
function makeChair(g:T.Group,plan:Plan,t:number,envelope:boolean){const pose=chairPose(plan,t);if(!pose)return;const c=plan.chair;g.position.set(pose.x,0,pose.z);g.rotation.y=pose.r*Math.PI/180;g.userData.itemId='chair';const m=mat('#343d3c',.72),fabric=mat('#4c5552',1),chrome=mat('#343d3c',.4);box(g,c.width*.85,3,c.depth*.76,0,18,1,fabric,2);box(g,c.width*.86,c.height-21,3,0,(c.height+21)/2,-c.depth/2+1.5,fabric,1.5);box(g,2.8,15,2.8,0,10,0,chrome,1);for(let i=0;i<5;i++){const a=i*Math.PI*2/5,r=c.base/2-1.5;const spoke=box(g,1.2,1.1,r,Math.sin(a)*r/2,3,Math.cos(a)*r/2,chrome,.35);spoke.rotation.y=a;const wheel=new T.Mesh(new T.CylinderGeometry(1.35,1.35,1.2,12),chrome);wheel.rotation.z=Math.PI/2;wheel.position.set(Math.sin(a)*r,1.5,Math.cos(a)*r);g.add(wheel);}if(c.arms)for(const s of [-1,1]){box(g,1.2,c.armHeight-18,1.4,s*(c.width/2-1),18+(c.armHeight-18)/2,1,chrome,.3);box(g,2,1.3,c.depth*.52,s*(c.width/2-1),c.armHeight-.6,1,m,.6);}if(envelope){const col=chairCollision(plan,t).length?'#c2513e':teal;const ring=new T.Mesh(new T.RingGeometry(c.base/2-.15,c.base/2+.15,64),new T.MeshBasicMaterial({color:col,side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.7;g.add(ring);line(g,[[-c.width/2,.65,-c.depth/2],[c.width/2,.65,-c.depth/2],[c.width/2,.65,c.depth/2],[-c.width/2,.65,c.depth/2],[-c.width/2,.65,-c.depth/2]],col,true);}}
export default function Scene(props:SceneProps){const host=useRef<HTMLDivElement>(null),latest=useRef(props);latest.current=props;const api=useRef<{refresh:()=>void;camera:()=>void;animate:()=>void}|null>(null);const [error,setError]=useState(false);
 useEffect(()=>{const el=host.current!;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true});}catch{setError(true);return;}renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;el.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Interactive 3D bedroom. Drag furniture to move; drag empty space to orbit.');renderer.domElement.tabIndex=0;
 const scene=new T.Scene();let root=new T.Group();scene.add(root);const hemi=new T.HemisphereLight('#eff7ff','#a6a195',2.5);scene.add(hemi);const sun=new T.DirectionalLight('#fff0d5',3.3);sun.position.set(20,200,200);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-180,right:180,top:180,bottom:-180,near:1,far:600});sun.shadow.bias=-.0005;sun.shadow.normalBias=.3;scene.add(sun);const fill=new T.DirectionalLight('#dae5ef',1.7);fill.position.set(250,150,-80);scene.add(fill);
 const ortho=new T.OrthographicCamera(-130,130,130,-130,.1,2000),persp=new T.PerspectiveCamera(68,1,.1,2000);let camera:T.Camera=ortho;let controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.maxPolarAngle=Math.PI/2-.04;controls.minZoom=.45;controls.maxZoom=4;let movingChair:T.Group|null=null;let redraw=0;const draw=()=>{cancelAnimationFrame(redraw);redraw=requestAnimationFrame(()=>{renderer.render(scene,camera);});};controls.addEventListener('change',draw);
 function resize(){const w=el.clientWidth,h=el.clientHeight;if(!w||!h)return;renderer.setSize(w,h);const maxRoom=Math.max(latest.current.plan.room.width,latest.current.plan.room.length);const span=Math.max(maxRoom*.87,maxRoom*.91/(w/h));ortho.left=-span*w/h;ortho.right=span*w/h;ortho.top=span;ortho.bottom=-span;ortho.updateProjectionMatrix();persp.aspect=w/h;persp.updateProjectionMatrix();draw();}
 function setCamera(){if(drag)up();const {plan,view}=latest.current;const {width:w,length:l}=plan.room;controls.dispose();camera=view==='room'?persp:ortho;camera.up.set(0,1,0);if(view==='plan'){camera.position.set(w/2,350,l/2);camera.up.set(0,0,-1);}else if(view==='room')camera.position.set(w*.82,62,l*.94);else camera.position.set(w/2+155,230,l/2+195);ortho.zoom=1;ortho.updateProjectionMatrix();controls=new OrbitControls(camera,renderer.domElement);controls.target.set(view==='room'?w*.4:w/2,view==='room'?30:0,view==='room'?l*.32:l/2);controls.enableRotate=view!=='plan';controls.maxPolarAngle=Math.PI/2-.04;controls.minZoom=.45;controls.maxZoom=4;controls.addEventListener('change',draw);controls.update();resize();}
 function disposeGroup(g:T.Group){const textures=new Set<T.Texture>(),materials=new Set<T.Material>();g.traverse(o=>{const mesh=o as T.Mesh;if(mesh.geometry)mesh.geometry.dispose();if(mesh.material){(Array.isArray(mesh.material)?mesh.material:[mesh.material]).forEach(m=>{materials.add(m);for(const v of Object.values(m))if(v instanceof T.Texture)textures.add(v);});}});textures.forEach(t=>t.dispose());materials.forEach(m=>m.dispose());}
 function refresh(){scene.remove(root);disposeGroup(root);root=new T.Group();scene.add(root);const p=latest.current,{plan,view}=p,{width:w,length:l,height:h}=plan.room;scene.background=new T.Color(p.night?'#263538':'#e9eeee');hemi.intensity=p.night?.8:2.5;sun.intensity=p.night?.8:3.3;fill.intensity=p.night?.4:1.7;const floorTex=woodTexture(plan.room.floor);floorTex.center.set(.5,.5);floorTex.rotation=Math.PI/2;floorTex.repeat.set(3,3);const floorMat=new T.MeshStandardMaterial({map:floorTex,roughness:.85});box(root,w+4,3,l+4,w/2,-1.8,l/2,mat('#d0d5d4'),.4);box(root,w,.3,l,w/2,-.05,l/2,floorMat);
 for(let x=0;x<w;x+=7){line(root,[[x,.16,0],[x,.16,l]],'#696f70');for(let z=18+(Math.floor(x/7)%3)*13;z<l;z+=49)line(root,[[x,.17,z],[Math.min(w,x+7),.17,z]],'#767c7d');}
 if(p.grid){for(let x=-150;x<=w+150;x+=12)line(root,[[x,-3.45,-150],[x,-3.45,l+150]],p.night?'#354547':'#d8dfdf');for(let z=-150;z<=l+150;z+=12)line(root,[[-150,-3.45,z],[w+150,-3.45,z]],p.night?'#354547':'#d8dfdf');}
 const wall=mat(plan.room.wall),base=mat('#ffffff');const wh=view==='plan'?1.5:view==='room'?h:62;box(root,plan.room.solid+2,wh,3,plan.room.solid/2-1,wh/2,-1.5,wall);box(root,3,wh,l+3,-1.5,wh/2,l/2,wall);box(root,3,view==='room'?h:3,l+3,w+1.5,(view==='room'?h:3)/2,l/2,wall);box(root,plan.room.solid,3,.7,plan.room.solid/2,1.5,.4,base);box(root,.7,3,l,.4,1.5,l/2,base);
 // Window width and height are illustrative. The measured front boundary remains exact.
 if(view!=='plan'){const frame=mat('#343f43',.4);box(root,w,2,2,w/2,1,l+1,frame);const winH=view==='room'?h:12;for(let x=0;x<=w+.1;x+=w/4)box(root,1.2,winH,1.2,x,winH/2,l+1,frame);if(view==='room'){box(root,w,1.5,1.5,w/2,h,l+1,frame);const glass=new T.MeshPhysicalMaterial({color:'#b1d1dd',transparent:true,opacity:.12,roughness:.1,side:T.DoubleSide});box(root,w,h,.2,w/2,h/2,l+1,glass);}}
 const a=analyze(plan),bed=plan.items.find(i=>i.id==='bed'&&i.visible),desk=plan.items.find(i=>i.id==='desk'&&i.visible);
 if(a.gap!==null&&bed&&desk){const x1=Math.max(bounds(bed).left,bounds(desk).left),x2=Math.min(bounds(bed).right,bounds(desk).right),z1=bounds(bed).front,z2=bounds(desk).rear;flatPoly(root,[{x:x1,z:z1},{x:x2,z:z1},{x:x2,z:z2},{x:x1,z:z2}],amber,.13);if(p.dimensions)dimension(root,[x2+4,1,z1],[x2+4,1,z2],a.gap.toFixed(1)+' in',amber);}
 if(p.drawers)for(const zone of drawerZones(plan))flatPoly(root,zone.poly,zone.blocked?'#c2513e':teal,.12);
 for(const item of plan.items.filter(i=>i.visible)){const group=new T.Group();root.add(group);furniture(group,item,p.selected===item.id,plan,p.drawers,outside(polygon(item),plan.room)||plan.items.some(other=>other.visible&&other.id!==item.id&&overlap(polygon(item),polygon(other))));if(view==='plan'&&p.dimensions)label(root,item.kind==='bed'?'BED · '+item.w+' × '+item.d:item.kind==='desk'?'DESK · '+item.w+' × '+item.d:item.name.replace('BRIMNES ','').toUpperCase(),item.x,item.h+5,item.z,'#2d4546',item.kind==='nightstand'?.6:1);}
 const chairG=new T.Group();movingChair=chairG;root.add(chairG);makeChair(chairG,plan,p.progress,p.envelope);if(p.envelope&&view==='plan'){for(const t of [0,.5,1]){const pose=chairPose(plan,t);if(pose){const color=chairCollision(plan,t).length?'#c2513e':teal;const circle=new T.EllipseCurve(pose.x,pose.z,plan.chair.base/2,plan.chair.base/2,0,Math.PI*2,false,0).getPoints(64);line(root,circle.map(v=>[v.x,.7,v.y]),color,true);}}}
 if(p.dimensions){dimension(root,[-10,1,0],[-10,1,l],l+' in');dimension(root,[0,1,l+13],[w,1,l+13],w+' in');dimension(root,[0,wh+4,-4],[plan.room.solid,wh+4,-4],plan.room.solid+' in');dimension(root,[plan.room.solid,1,-8],[w,1,-8],(w-plan.room.solid).toFixed(0)+' in opening');}draw();}
 const ray=new T.Raycaster(),pointer=new T.Vector2(),plane=new T.Plane(new T.Vector3(0,1,0),0);let drag:{id:string;dx:number;dz:number;x:number;z:number;px:number;py:number;moved:boolean}|null=null;function ground(e:PointerEvent){const b=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);ray.setFromCamera(pointer,camera);const v=new T.Vector3();return ray.ray.intersectPlane(plane,v);}
 function down(e:PointerEvent){if(e.button!==0)return;const v=ground(e);const hit=ray.intersectObjects(root.children,true).find(h=>{let o:T.Object3D|null=h.object;while(o){if(o.userData.itemId)return true;o=o.parent;}return false;});if(!hit)return;let o:T.Object3D|null=hit.object;while(o&&!o.userData.itemId)o=o.parent;const id=o?.userData.itemId;if(!id)return;latest.current.onSelect(id);const item=latest.current.plan.items.find(i=>i.id===id);if(item&&!item.locked&&v){drag={id,dx:item.x-v.x,dz:item.z-v.z,x:item.x,z:item.z,px:e.clientX,py:e.clientY,moved:false};controls.enabled=false;renderer.domElement.setPointerCapture(e.pointerId);e.stopImmediatePropagation();}}
 function move(e:PointerEvent){if(!drag)return;if((e.buttons&1)===0){up();return;}if(!drag.moved&&Math.hypot(e.clientX-drag.px,e.clientY-drag.py)<4)return;drag.moved=true;const v=ground(e);if(!v)return;const snap=latest.current.snap?.5:.05;drag.x=Math.round((v.x+drag.dx)/snap)*snap;drag.z=Math.round((v.z+drag.dz)/snap)*snap;latest.current.onMove(drag.id,drag.x,drag.z,false);}
 function up(){if(drag){if(drag.moved)latest.current.onMove(drag.id,drag.x,drag.z,true);drag=null;controls.enabled=true;}}
 renderer.domElement.addEventListener('pointerdown',down,true);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointercancel',up);renderer.domElement.addEventListener('lostpointercapture',up);window.addEventListener('pointerup',up,true);window.addEventListener('blur',up);const observer=new ResizeObserver(resize);observer.observe(el);api.current={refresh,camera:setCamera,animate:()=>{if(movingChair){const pose=chairPose(latest.current.plan,latest.current.progress);if(pose){movingChair.position.set(pose.x,0,pose.z);movingChair.rotation.y=pose.r*Math.PI/180;const color=chairCollision(latest.current.plan,latest.current.progress).length?'#c2513e':teal;movingChair.traverse(o=>{if(o instanceof T.Line && o.material instanceof T.LineDashedMaterial)o.material.color.set(color);if(o instanceof T.Mesh&&o.geometry instanceof T.RingGeometry)(o.material as T.MeshBasicMaterial).color.set(color);});}}draw();}};setCamera();refresh();props.onReady?.(()=>{renderer.render(scene,camera);return renderer.domElement.toDataURL('image/png');});return()=>{window.removeEventListener('pointerup',up,true);window.removeEventListener('blur',up);observer.disconnect();cancelAnimationFrame(redraw);controls.dispose();disposeGroup(root);sun.shadow.map?.dispose();renderer.dispose();renderer.domElement.remove();api.current=null;};
 },[]);
 useEffect(()=>{api.current?.refresh();},[props.plan,props.selected,props.grid,props.dimensions,props.drawers,props.envelope,props.night,props.view]);
 useEffect(()=>{api.current?.animate();},[props.progress]);
 useEffect(()=>{api.current?.camera();},[props.view,props.reset]);
 return <div ref={host} className="scene-host">{error&&<div className="canvas-error">This browser could not start 3D graphics. Try Chrome or Safari with hardware acceleration enabled.</div>}</div>;
}
